environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python
    #- PYTHON: "C:\\Python27"
    #  PYTHON_VERSION: "2.7.14"
    #  PYTHON_ARCH: "32"

    #- PYTHON: "C:\\Python27-x64"
    #  PYTHON_VERSION: "2.7.14"
    #  PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "64"

    # - PYTHON: "C:\\Python39"
    #   PYTHON_VERSION: "3.9.0"
    #   PYTHON_ARCH: "32"
    # - PYTHON: "C:\\Python39-x64"
    #   PYTHON_VERSION: "3.9.0"
    #   PYTHON_ARCH: "64"

for:
  - matrix:
      only:
        - image: "Visual Studio 2019"
        - PYTHON: "C:\\Python39"
        - PYTHON: "C:\\Python39-x64"
  - matrix:
      exclude:
        - image: "Visual Studio 2013"
        - PYTHON: "C:\\Python39"
        - PYTHON: "C:\\Python39-x64"

branches:
  only:
    - master

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "%CMD_IN_ENV% %PYTHON%\\python.exe -m pip install pytest"
  - "%CMD_IN_ENV% %PYTHON%\\python.exe setup.py build_ext --inplace"

build_script:
  - "ECHO %WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"

test_script:
  - "%CMD_IN_ENV% %PYTHON%/python.exe -m pytest -sv"

artifacts:
  - path: "dist\\*.whl"
#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
