[tox]
requires =
    tox>=4.11
    tox-uv>=1
envlist=py38,py39,py310,py311,py312,py313,py314
skip_missing_interpreters = True
toxworkdir={toxinidir}/../simpleparse-tox


[testenv]
runner = uv-venv-runner
deps=pytest
usedevelop=true
commands=pytest {posargs:tests}
